version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - "~/.cargo"
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.34.0
            source $HOME/.cargo/env
            npm run test

      - run: npm run codecov-upload
